
[env]
TERM = "alacritty"

[font]
size = 18

[font.normal]
family = "Menlo"

[font.offset]
x = -1
y = -4

[general]
import = ["$HOME/.config/alacritty/base16-tomorrow-night.yml"]

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[colors]
draw_bold_text_with_bright_colors = false

[terminal]
