#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc -m 1 &

xset r rate 225 150
setxkbmap -option ctrl:nocaps

feh --bg-scale $HOME/Pictures/Wallpapers/lucian_vs_thresh_league_of_legends_fan_art_by_ashot94_ddpja28-fullview.jpg
picom -b

bash ~/.config/polybar/launch.sh
/usr/lib/x86_64-linux-gnu/libexec/kdeconnectd &
/usr/bin/nm-applet &

bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9

bspc config border_width                  1
bspc config focused_border_color          "#a3685a"
bspc config window_gap                    8
bspc config focus_follow_pointer          true


bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a Teams desktop='^4'
bspc rule -a Firefox desktop='^9' follow=on
bspc rule -a Nautilus desktop='^3' follow=on
